### ISSUE TITLE
TimesTen data type

### ISSUE THREAD

**Issue by ebayaraa** [rana/ora#116]
I'm connecting TimesTen DB and query with TT_BIGINT data type.
TT_BIGINT's code is SQLT_INT.
Please add this data code.

**Comment by tgulacsi** [comment]
I don't have a TimesTen DB, so I can't test it - please be a little bit more verbose: what code does the DB report for the column type? How should that be treated?

**Comment by tgulacsi** [comment]
As far as I read (https://docs.oracle.com/cd/E18283_01/timesten.112/e13076/dtypesfunc.htm), TimesTen adds TT_BIGINT as a new column datatype.
As this is just an int64, we could read it from the resultsets without any conversion, but for such columns, the actual defInt64 does not work, needs some modification to use int64 instead of OCINumber.

The first step would be knowing what does TimesTen report for such a column:

    SELECT DUMP(tt_bigint_col) FROM table_with_tt_bigint_col_column WHERE ROWNUM < 2;

Then some test possibility is needed...

**Comment by ebayaraa** [comment]
Got following error in timesten:
 2818: Unknown function DUMP
The command failed.

But my problem solved after I added SQLT_INT in rset.go:
```
...
        for n := range rset.defs {
                ocipar := params[n].param
                ociTypeCode := params[n].typeCode
                columnSize := params[n].columnSize

                switch ociTypeCode {
                case C.SQLT_NUM, C.SQLT_INT:
                        // NUMBER
                        // Get precision
                        var precision C.sb2
                        err = rset.paramAttr(ocipar, unsafe.Pointer(&precision), nil, C.OCI_ATTR_PRECISION)
                        if err != nil {
                                return err
                        }
...
```
