### ISSUE TITLE
how to close oracle automaic diagnostic 

### ISSUE THREAD

**Issue by dingkaich** [rana/ora#177]
I have a issue ,if i use go-ora ,it will enable automatic  diagnostic ?
how to close oracle automaic diagnostic  in ora.v3?

**Comment by tgulacsi** [comment]
What is "automatic diagnostic" ?

Kai ding <notifications@github.com> ezt írta (időpont: 2017. márc. 23., Cs,
8:42):

**Comment by dingkaich** [comment]
In normal oracle client，
we can set /opt/oracle/product/11gR2/db/network/admin/sqlnet.ora to disable it  like this:
diag_adr_enabled = OFF.
adr_base = /oracle/network/trace


Also， you can access this web site https://oracle-base.com/articles/11g/automatic-diagnostics-repository-11gr1   to learn more adr..

help me please.

**Comment by tgulacsi** [comment]
As far as I understand, ADR is a server-side thing, and ora is a client,
and you cannot alter this behavior from the client.

Kai ding <notifications@github.com> ezt írta (időpont: 2017. márc. 24., P
3:37):

**Comment by dingkaich** [comment]
I have another  project using C++ with SQLAPI  and oracle 11g client.
If I set below in /opt/oracle/app/product/11gR2/db/network/admin/sqlnet.ora  , it will be closed.
DIAG_SIGHANDLER_ENABLED=FALSE
DIAG_ADR_ENABLED=OFF
DIAG_DDE_ENABLED=FALSE

I set it in oracle client side and it works !

Should our ora.V3/V4 have no api to do this ? 

I think this is same with configure in client sqlnet.ora like SQLNET.RECV_TIMEOUT and 
SQLNET.SEND_TIMEOUT. 


thanks

**Comment by tgulacsi** [comment]
sqlnet.ora an tnsnames.ora are used by the Oracle client library AFAIK, the
ora driver has no effect on them.
But you can prove me wrong if you show what OCI calls are needed to tweak
those params.

https://boomslaang.wordpress.com/tag/diag_adr_enabled/ and
http://dbmentors.blogspot.hu/2011/01/using-and-disabling-automatic.html
says setting the proper sqlnet.ora is enough.

What kind of client do you use? Instant Client or a full Oracle RDBMS's
library?

http://dba.stackexchange.com/a/80662 suggests that TNS_ADMIN and
ORACLE_HOME should be set proper to allow the client to find sqlnet.ora.

Kai ding <notifications@github.com> ezt írta (időpont: 2017. márc. 24., P,
6:53):

**Comment by dingkaich** [comment]
i just inclue your goora in my project . , and I can't find sqlnet.ora in any directory ?
no ORACLE_HOME is be set. I never set ORACLE_HOME.
could you tell me how to find sqlnet.ora?
Maybe , How to set ORACLE_HOME?

**Comment by tgulacsi** [comment]
As I wrote,you have to find your Oracle Client library's sqlnet.ora.

The easiest is to check where is your libclntsh.so, for example by
compiling your app and check what ldd says, where is libclnts.so.

For example:

$ ldd ws-server
        linux-vdso.so.1 (0x00007ffcdebca000)
        libclntsh.so.12.1 =>
/usr/lib/oracle/12.1/client64/lib/libclntsh.so.12.1 (0x00007f23f50c7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007f23f4eaa000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f23f4b0c000)
        libmql1.so => /usr/lib/oracle/12.1/client64/lib/libmql1.so
(0x00007f23f4896000)
        libipc1.so => /usr/lib/oracle/12.1/client64/lib/libipc1.so
(0x00007f23f4518000)
        libnnz12.so => /usr/lib/oracle/12.1/client64/lib/libnnz12.so
(0x00007f23f3e0c000)
        libons.so => /usr/lib/oracle/12.1/client64/lib/libons.so
(0x00007f23f3bc7000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f23f39c3000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f23f36bf000)
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1
(0x00007f23f34a7000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f23f329f000)
        /lib64/ld-linux-x86-64.so.2 (0x000055ce0725f000)
        libaio.so.1 => /lib/x86_64-linux-gnu/libaio.so.1
(0x00007f23f309b000)
        libclntshcore.so.12.1 =>
/usr/lib/oracle/12.1/client64/lib/libclntshcore.so.12.1 (0x00007f23f2b29000)

I use Oracle Instant Client, which does not have sqlnet.ora, though...

But I set TNS_ADMIN=$HOME/.config/oracle and store tnsnames.ora there.

Kai ding <notifications@github.com> ezt írta (időpont: 2017. márc. 24., P
8:50):

i just inclue your goora in my project . , and I can't find sqlnet.ora in
any directory ?
no ORACLE_HOME is be set. I never set ORACLE_HOME.
could you tell me how to find sqlnet.ora?
Maybe , How to set ORACLE_HOME?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/rana/ora/issues/177#issuecomment-288955444>, or mute
the thread

**Comment by dingkaich** [comment]
thank you very much !!!
I set TNS_ADMIN, and it works !! 
I love u！！！！ wish you have a nice day everyday!!
