### ISSUE TITLE
With database/sql, cursors stay open

### ISSUE THREAD

**Issue by tgulacsi** [rana/ora#21]
I'm using database/sql, and I have a connection which shall stay opened, and query a view once for every 15 second.

Either conn.Query + defer rows.Close, or conn.Prepare + defer stmt.Close + stmt.Query + defer rows.Close, number of opened cursors just grows, till (after 1000/4 = 250 minutes) it fails with "Too many opened cursors".

I've tried adding rset.autoClose in drvQueryRows.go, without avail (closing in drvStmt.Close caused panics).

I'll try to create a reproduction, but do you have an idea, how to fix this?

Thanks,
Tamás Gulácsi

**Comment by tgulacsi** [comment]
See 7601cc04c90eeb6186185c20363dcb7ff708f236 (Test_open_cursors_db) for a reproducing case.

**Comment by rana** [comment]
I do suspect the driver of keeping open cursors, but am unsure if it is. It certainly sounds like it. I initially looked into it but wasn't able to find out.

**Comment by tgulacsi** [comment]
It is the same with non-driver code: see Test_open_cursors in z_session_test.go

Why is this automatic ResultSet management? I'm not sure that not that's the problem's source...

**Comment by rana** [comment]
I think you're right. Its a general issue not specific to database/SQL.
Automatic rset management was added for database/SQL and general ease of
use. If auto management is the issue it should be fixed or removed.

It might be related to rest pooling or at the oci level. When I looked at
open cursors in oracle they would be reduced after time. So, does that mean
the driver opens them quickly and oracle eventually cleans them up? Or
there is a leak?

I will have a closer look at test_open_cursors.

**Comment by tgulacsi** [comment]
I've added Test_open_cursors_db to goracle, and there it passes.
Goracle uses OCIStmtPrepare2 & OCIStmtRelease; I've tried to add it to ora, but didn't work: after OCIStmtPrepare2 (instead of OCIStmtPrepare), I get ORA-24337: statement handle not prepared.
In retrospect, maybe that's because of how I declared the pointer to ocistmt.

Now I've tried it again, and WORKS! See my PR.

**Comment by rana** [comment]
Awesome!

**Comment by rana** [comment]
I was reviewing the open cursor issue, docs and tests.


[Statement Caching in OCI](https://docs.oracle.com/database/121/LNOCI/oci09adv.htm#LNOCI16655) says that [OCIStmtPrepare2](https://docs.oracle.com/database/121/LNOCI/oci17msc001.htm#LNOCI171680) must be followed with a call to [OCIStmtRelease](https://docs.oracle.com/database/121/LNOCI/oci17msc001.htm#LNOCI17169). And according to Oracle, "A call to OCIStmtPrepare2(), even if the session does not have a statement cache, also allocates the statement handle. Therefore, applications using only OCIStmtPrepare2() must not call OCIHandleAlloc() for the statement handle."

Separately, [OCIStmtPrepare](https://docs.oracle.com/database/121/LNOCI/oci17msc001.htm#LNOCI17167) can be followed by a call to [OCIHandleFree](https://docs.oracle.com/database/121/LNOCI/oci16rel002.htm#LNOCI17135).

If you want to read more about it, the [Oracle docs](https://docs.oracle.com/database/121/LNOCI/oci09adv.htm#LNOCI16655) have some good guidance on the matter.

I also fixed a bug in Test_open_cursors to use 'opened cursors current' STATISTIC#=5 to determine the number of open cursors. I think this issue is closed due to your bug fix. In my test, The number of open cursors was 2 before the test and 3 after the test. The increase in cursor count was due to querying the number of cursors. 

So your code fixed the issue. Thank you!

**Comment by tgulacsi** [comment]
I've read that paragraph several times, but it doesn't say why an OCIStmtPrepare + OCIHandleFree would leave cursors open...

Anyway, thanks for the cleanup!
