### ISSUE TITLE
Call sql.Register from inside the driver

### ISSUE THREAD

**Issue by ricsmania** [rana/ora#41]
One of the things that bothers me about Rana is the need to call ora.Register on my program. Goracle and Go-oci8 both call sql.Register inside the driver itself, so whoever is using them doesn't need to. Any reason not to modify Rana to do the same?

**Comment by rana** [comment]
Tamás,

What do you think?

Rana

**Comment by tgulacsi** [comment]
I've never really understood why do we need that Register, and it bothered me a little bit.
But shrugged, and used it.

AFAIK this is for setting the base config values. I even understand why is that needed before use the driver: otherwise it may have no effect (on alredy opened env, srv, ses and rset).

Maybe a big warning in the documentation, that if you want to set the config, then use Register, but the driver would set the configs just as if you've called ora.Register(nil) before?
Of course init() have to register itself on database/sql, then, without Register.

This way we could "just use" "ora" driver, but also allow debug/non-default usage (RsetCfg) with a well timed call on Register.
And then Register becomes a bad name, "SetCfg" or "SetDrvCfg" or "SetEnvCfg" would be better.

**Comment by rana** [comment]
Sounds good.
Are you inspired to make the changes?
Or, would you like me to?

**Comment by rana** [comment]
@tgulacsi  Thank you for all those changes Tamás.
At the next version I'll remove 'Register'.

@ricsmania better?

**Comment by ricsmania** [comment]
@rana @tgulacsi it's much better now, thank you very much!

I know this may seem minor, but it was the only thing that prevented Rana from having 100% compatibility with Goracle and Go-oci8 in database/sql mode. I'm currently making lots of tests with those 3 drivers, and this makes my life much easier.

**Comment by ricsmania** [comment]
@tgulacsi I have noticed a small problem when trying to set a driver config. SetDrvCfg apparently does nothing, no matter if I put in the init() func or beforing opening the database.

I could, however, change the config using something like this:

```go
ora.Cfg().Env.StmtCfg.Rset.SetChar(ora.S)
ora.Cfg().Env.StmtCfg.Rset.SetChar1(ora.S)
```

Is there a specific place to call SetDrvCfg in order for it to work? Or maybe the documentation should point to using ora.Cfg()?

Also, creating a test for it might be interesting, what do you think? I can create the test once I know the expected behavior. I was thinking about something like this:

```go
package main

import (
	"database/sql"
	"fmt"
	"gopkg.in/rana/ora.v3"
)

func setDrv() {
	drvCfg := ora.NewDrvCfg()
	drvCfg.Env.StmtCfg.Rset.SetChar(ora.S)
	drvCfg.Env.StmtCfg.Rset.SetChar1(ora.S)
	ora.SetDrvCfg(drvCfg)
}

func init() {
	// This doesn't work
	setDrv()
}

func main() {
	// This works
	ora.Cfg().Env.StmtCfg.Rset.SetChar(ora.S)
	ora.Cfg().Env.StmtCfg.Rset.SetChar1(ora.S)
	db, err := sql.Open("ora", "system/mega@pc_leandroa/wine")
	if err != nil {
		panic(err)
	}
	query := "select cast('S' as char(1)) from dual"
	rows, err := db.Query(query)
	if err != nil {
		panic(err)
	}

	var value string

	for rows.Next() {
		rows.Scan(&value)
		// This should print 'S', not 'false'
		fmt.Println(value)
	}
}

```

**Comment by tgulacsi** [comment]
Sorry for the inconvenience. Can you try c53d361?
(cd $GOPATH/src/gopkg.in/rana/ora.v3 && git fetch origin && git checkout -b register origin/register && go install)

I've added TestDrvCfg at the end of z_oracle_test.go, so if this is not enough, please try to enhance that test.

**Comment by ricsmania** [comment]
@tgulacsi No inconvenience caused, don't worry. It works now, thank you very much!

**Comment by tgulacsi** [comment]
Ok, then I merge it to master.
