### ISSUE TITLE
CHAR(1) is treated as bool, looses information

### ISSUE THREAD

**Issue by tgulacsi** [rana/ora#82]
The default `SetChar(ora.B)` feature treats every `CHAR(1)` column as a boolean. And not just with `ora.Prep`, but with `sql.Open`, too!

We use CHAR(1) columns not just for booleans, but for state marks, too (X/Y/Z, B/K ...).

I'd like to turn off this feature (it is a misfeature to me, to be honest), as I've started at master (9b329a8df91bf53a8d624617d21549abb4442b37), but first I'd like to ask you for confirmation: is this feature frequently used? Would this change affect a lot of precious code badly?

**Comment by rana** [comment]
How would you handle Go bool values by default?

**Comment by tgulacsi** [comment]
A bool is ok, but don't treat CHAR(1) columns as bool by default.

**Comment by rana** [comment]
That's fine if you'd like to change the default char(1) behavior.

**Comment by tgulacsi** [comment]
Ok, thanks!

**Comment by rana** [comment]
Would this be a breaking change for some? Do we need a new version for
gopkg.in?

**Comment by tgulacsi** [comment]
That's a good question. API per se does not change, "just" the defaults.
But if we didn't created a new version for the ora.N change (OCINum instead of string), then this wouldn't need a new version, either.

**Comment by rana** [comment]
Ya.

What do you think of golang's 'vendoring' feature?
Does that replace the need for gopkg.in?

**Comment by tgulacsi** [comment]
Yes and no. With gopkg.in, we swear that we won't change the API in the same major version; with vendoring, users can hedge against changes.
I think as a library writer, you don't need vendoring; as a library user/consumer, you want it very much.

Do we have any non-standard dependency in ora? `go list -f '{{range .Imports}}{{println . }}{{end}}'` lists only gopkg.in/rana/ora.v3/num which is a subpackage - already vendored in.

**Comment by rana** [comment]
The main Ora package just use the standard library. The logging bits use
other go libraries
On Apr 18, 2016 12:58 PM, "Tamás Gulácsi" <notifications@github.com> wrote:

Yes and no. With gopkg.in, we swear that we won't change the API in the
same major version; with vendoring, users can hedge against changes.
I think as a library writer, you don't need vendoring; as a library
user/consumer, you want it very much.

Do we have any non-standard dependency in ora? go list -f '{{range
.Imports}}{{println . }}{{end}}' lists only gopkg.in/rana/ora.v3/num which
is a subpackage - already vendored in.

—
You are receiving this because you were assigned.

Reply to this email directly or view it on GitHub
<https://github.com/rana/ora/issues/82#issuecomment-211550965>

**Comment by tgulacsi** [comment]
Logging: I agree with [Dave Cheney](http://dave.cheney.net/2015/11/05/lets-talk-about-logging) that a Debug and an Info level is adequate - maybe for a library, Debug is enough, as errors are reported back, and should contain enough info to localize them anyway.

The main idea I've read I cannot find now: in a library, logging should be through global settable vars - such as
```
var Debug func(string, ...interface{})
```
so the library user can provide and use any kind of logger she wishes, just provide a proper function!

**Comment by rana** [comment]
Nice!
I love the blog post and idea of offering Debug func and Info func.
Were you thinking of adding Debug func and Info func?
